# Generated by Django 5.2.3 on 2025-07-02 14:47

import django.db.models.deletion
import labapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity_available", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                ("course", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(default=labapp.models.get_india_time),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_issued", models.IntegerField()),
                ("date_issued", models.DateTimeField(auto_now_add=True)),
                ("returned", models.BooleanField(default=False)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labapp.component",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labapp.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Working", "Working"),
                            ("Not Working", "Not Working"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_returned", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labapp.issuerecord",
                    ),
                ),
            ],
        ),
    ]
